AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Lint/Eval:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Description: >-
                 Compact style ensures that the parent classes and modules are not reopened for each child class and
                 module.  Reopening the parent class or module can lead to the parent class or module not being loaded
                 as the child already defined it.
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Description: >-
                 Modifiers prevent placing break points on just the condition or just the body.  Similarly, coverage of
                 the line cannot tell you if the body is ever executed.
  Enabled: false
Style/IndentationConsistency:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/NegatedWhile:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/SpaceAroundOperators:
  Enabled: false
Style/SpaceBeforeBlockBraces:
  Enabled: false
Style/SpaceBeforeComma:
  Enabled: false
Style/SpaceInsideBlockBraces:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  Enabled: false
Style/SpaceInsideParens:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/TrivialAccessors:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
